version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
  profiles:
    active: prod

swagger:
  enabled: true

